POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "abc@gmail.com",
    "password": "123"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "abc@gmail.com",
    "password": "123"
}
###

GET http://localhost:3000/api/sauces/60c36436635caf29148955a8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGJhMjVlOWFhYTcxYjJjZDg5Yjc3MjMiLCJpYXQiOjE2MjI4MTc3NTUsImV4cCI6MTYyMjkwNDE1NX0.SWAFofvUBv-sixUzbRAIXukLDUeEjkpZhjD2gx6HxH8

###
PUT http://localhost:3000/api/stuff/60b0f0dd095c5c02604c7c55
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGJhMjVlOWFhYTcxYjJjZDg5Yjc3MjMiLCJpYXQiOjE2MjI4MTc3NTUsImV4cCI6MTYyMjkwNDE1NX0.SWAFofvUBv-sixUzbRAIXukLDUeEjkpZhjD2gx6HxH8
Content-Type: application/json

{
    "title":"new laptop",
    "userId": "60b0ee39095c5c02604c7c53"
}


###
POST http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGJhMjVlOWFhYTcxYjJjZDg5Yjc3MjMiLCJpYXQiOjE2MjI4MTc3NTUsImV4cCI6MTYyMjkwNDE1NX0.SWAFofvUBv-sixUzbRAIXukLDUeEjkpZhjD2gx6HxH8
Content-Type: application/json

{"sauce":
{
  "userId":"123",
  "name": "bechamel",
  "manufacturer": "italie",
  "description": "tres bon",
  "mainPepper": "lait",
  "imageUrl": "",
  "heat": 5,
  "likes": "",
  "dislikes": "",
  "usersLiked": "",
  "usersDisliked": ""
}}