POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "abc@gmail.com",
    "password": "123"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "abc@gmail.com",
    "password": "123"
}
###

GET http://localhost:3000/api/sauces/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGJhMjVlOWFhYTcxYjJjZDg5Yjc3MjMiLCJpYXQiOjE2MjQwMjM5MjIsImV4cCI6MTYyNDExMDMyMn0.xW7tWGTsWSxF59NCBcVCqiiMl8erTiy_Hk2OvjG6q14

###
PUT http://localhost:3000/api/sauces/60cc5e81a6e14c10dc304752
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGJhMjVlOWFhYTcxYjJjZDg5Yjc3MjMiLCJpYXQiOjE2MjQwMjM5MjIsImV4cCI6MTYyNDExMDMyMn0.xW7tWGTsWSxF59NCBcVCqiiMl8erTiy_Hk2OvjG6q14
Content-Type: application/json

{
    "name":"new laptop"
}


###
POST http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGJhMjVlOWFhYTcxYjJjZDg5Yjc3MjMiLCJpYXQiOjE2MjI4MTc3NTUsImV4cCI6MTYyMjkwNDE1NX0.SWAFofvUBv-sixUzbRAIXukLDUeEjkpZhjD2gx6HxH8
Content-Type: application/json

{"sauce":
{
  "userId":"123",
  "name": "bechamel",
  "manufacturer": "italie",
  "description": "tres bon",
  "mainPepper": "lait",
  "imageUrl": "",
  "heat": 5,
  "likes": "",
  "dislikes": "",
  "usersLiked": "",
  "usersDisliked": ""
}}